import { Bill, Product } from "@/types";

export const getBills = () => {
  const bills = localStorage.getItem("bills");
  return bills ? JSON.parse(bills) : [];
};

export const addBill = (bill: Bill) => {
  const bills = getBills();
  localStorage.setItem("bills", JSON.stringify([...bills, bill]));
};

export const removeLastBill = () => {
  const bills = getBills();
  if (bills.length > 0) {
    bills.pop(); // Remove the last bill
    localStorage.setItem("bills", JSON.stringify(bills));
  }
};

export const clearBills = () => {
  localStorage.setItem("bills", JSON.stringify([]));
};

const HIDDEN_CATEGORIES = {
  cantina: ["ASCUNSE"],
  viva: ["ASCUNSE"],
};

export const initializeProducts = (location: "cantina" | "viva") => {
  const vivaProducts: Product[] = [
    {
      id: "1",
      name: "Espresso",
      price: 8,
      category: "CAFEA",
      location: "viva",
      barcode: "123456789",
    },
    {
      id: "2",
      name: "Cappuccino",
      price: 12,
      category: "CAFEA",
      location: "viva",
      barcode: "223456789",
    },
    {
      id: "3",
      name: "Coca Cola",
      price: 7,
      category: "BAUTURI",
      location: "viva",
      barcode: "323456789",
    },
    {
      id: "4",
      name: "Tiramisu",
      price: 15,
      category: "DESERT",
      location: "viva",
      barcode: "423456789",
    },
    {
      id: "hidden1",
      name: "Produs Ascuns",
      price: 10,
      category: "ASCUNSE",
      location: "viva",
      barcode: "999999999",
      hidden: true,
    },
  ];

  const cantinaProducts: Product[] = [
    {
      id: "1",
      name: "cola zero ciob 0.33",
      price: 7,
      category: "BAUTURI",
      location: "cantina",
      barcode: "59492641",
    },
    {
      id: "2",
      name: "cola zero doza 0.33",
      price: 7,
      category: "BAUTURI",
      location: "cantina",
      barcode: "5942321000091",
    },
    {
      id: "3",
      name: "cola doza 0.33",
      price: 7,
      category: "BAUTURI",
      location: "cantina",
      barcode: "5942321000046",
    },
    {
      id: "4",
      name: "sprite doza 0.33",
      price: 7,
      category: "BAUTURI",
      location: "cantina",
      barcode: "5942321000282",
    },
    {
      id: "5",
      name: "fanta doza 0.33",
      price: 7,
      category: "BAUTURI",
      location: "cantina",
      barcode: "5942321000152",
    },
    {
      id: "6",
      name: "schweppes mojito doza 0.33",
      price: 7,
      category: "BAUTURI",
      location: "cantina",
      barcode: "5942321002798",
    },
    {
      id: "7",
      name: "schweppes bitter doza 0.33",
      price: 7,
      category: "BAUTURI",
      location: "cantina",
      barcode: "5942321000367",
    },
    {
      id: "8",
      name: "schweppes tonic doza 0.33",
      price: 7,
      category: "BAUTURI",
      location: "cantina",
      barcode: "5942321000381",
    },
    {
      id: "9",
      name: "schweppes mandarin doza 0.33",
      price: 7,
      category: "BAUTURI",
      location: "cantina",
      barcode: "5942321000350",
    },
    {
      id: "10",
      name: "burn 0.25",
      price: 7,
      category: "BAUTURI",
      location: "cantina",
      barcode: "5940620000057",
    },
    {
      id: "11",
      name: "burn 0.5",
      price: 12.5,
      category: "BAUTURI",
      location: "cantina",
      barcode: "5940620000040",
    },
    {
      id: "12",
      name: "jumex",
      price: 12.5,
      category: "BAUTURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "13",
      name: "cola pet 0.5",
      price: 8.2,
      category: "BAUTURI",
      location: "cantina",
      barcode: "59492573",
    },
    {
      id: "14",
      name: "cola pet zero 0.5",
      price: 8.2,
      category: "BAUTURI",
      location: "cantina",
      barcode: "59492702",
    },
    {
      id: "15",
      name: "sprite pet 0.5",
      price: 8.2,
      category: "BAUTURI",
      location: "cantina",
      barcode: "59492610",
    },
    {
      id: "16",
      name: "fuzetea menta pet 0.5",
      price: 8.2,
      category: "BAUTURI",
      location: "cantina",
      barcode: "59492757",
    },
    {
      id: "17",
      name: "fuzetea fructe padure pet 0.5",
      price: 8.2,
      category: "BAUTURI",
      location: "cantina",
      barcode: "59492726",
    },
    {
      id: "18",
      name: "fuzetea citronela pet 0.5",
      price: 8.2,
      category: "BAUTURI",
      location: "cantina",
      barcode: "59492733",
    },
    {
      id: "19",
      name: "fuzetea piersici pet 0.5",
      price: 8.2,
      category: "BAUTURI",
      location: "cantina",
      barcode: "59492719",
    },
    {
      id: "20",
      name: "apa viva plata 0.5",
      price: 5.5,
      category: "BAUTURI",
      location: "cantina",
      barcode: "5942324200603",
    },
    {
      id: "21",
      name: "apa viva minerala 0.5",
      price: 5.5,
      category: "BAUTURI",
      location: "cantina",
      barcode: "5942324200597",
    },
    {
      id: "22",
      name: "apa evian 0.5",
      price: 10.5,
      category: "BAUTURI",
      location: "cantina",
      barcode: "3068320055008",
    },
    {
      id: "23",
      name: "schweppes mandarin pet 0.5",
      price: 8.2,
      category: "BAUTURI",
      location: "cantina",
      barcode: "59492603",
    },
    {
      id: "24",
      name: "schweppes tonic pet 0.5",
      price: 8.2,
      category: "BAUTURI",
      location: "cantina",
      barcode: "59492740",
    },
    {
      id: "25",
      name: "schweppes bitter pet 0.5",
      price: 8.2,
      category: "BAUTURI",
      location: "cantina",
      barcode: "59492634",
    },
    {
      id: "26",
      name: "schweppes pink pet 0.5",
      price: 8.2,
      category: "BAUTURI",
      location: "cantina",
      barcode: "59492764",
    },
    {
      id: "27",
      name: "dorna minerala 2L",
      price: 7.6,
      category: "BAUTURI",
      location: "cantina",
      barcode: "5942321000657",
    },
    {
      id: "28",
      name: "dorna plata 2L",
      price: 7.6,
      category: "BAUTURI",
      location: "cantina",
      barcode: "5942321000572",
    },
    {
      id: "29",
      name: "bomboane raffaello",
      price: 22,
      category: "SNACKS",
      location: "cantina",
      barcode: "8000500023976",
    },
    {
      id: "30",
      name: "pergale milk",
      price: 20,
      category: "SNACKS",
      location: "cantina",
      barcode: "4770179998281",
    },
    {
      id: "31",
      name: "pergale champagne",
      price: 20,
      category: "SNACKS",
      location: "cantina",
      barcode: "4770179991459",
    },
    {
      id: "32",
      name: "praline cachet",
      price: 42,
      category: "SNACKS",
      location: "cantina",
      barcode: "5412956120377",
    },
    {
      id: "33",
      name: "mars cookies",
      price: 20,
      category: "SNACKS",
      location: "cantina",
      barcode: "5060402909566",
    },
    {
      id: "34",
      name: "bounty cookies 180g",
      price: 20,
      category: "SNACKS",
      location: "cantina",
      barcode: "5060402907661",
    },
    {
      id: "35",
      name: "toblerone",
      price: 18,
      category: "SNACKS",
      location: "cantina",
      barcode: "7614500010013",
    },
    {
      id: "36",
      name: "twix secret centre",
      price: 20,
      category: "SNACKS",
      location: "cantina",
      barcode: "5056357911747",
    },
    {
      id: "37",
      name: "lion duo choco",
      price: 18,
      category: "SNACKS",
      location: "cantina",
      barcode: "7613287756565",
    },
    {
      id: "38",
      name: "lion 42g",
      price: 8,
      category: "SNACKS",
      location: "cantina",
      barcode: "7613287757067",
    },
    {
      id: "39",
      name: "lion white 42g",
      price: 8,
      category: "SNACKS",
      location: "cantina",
      barcode: "7613034120151",
    },
    {
      id: "40",
      name: "mars 51g",
      price: 10,
      category: "SNACKS",
      location: "cantina",
      barcode: "5900951313417",
    },
    {
      id: "41",
      name: "mars protein 50g",
      price: 18,
      category: "SNACKS",
      location: "cantina",
      barcode: "5000159516198",
    },
    {
      id: "42",
      name: "mars protein raspberry 55g",
      price: 20,
      category: "SNACKS",
      location: "cantina",
      barcode: "5056357912539",
    },
    {
      id: "43",
      name: "snickers protein white",
      price: 20,
      category: "SNACKS",
      location: "cantina",
      barcode: "5056357909546",
    },
    {
      id: "44",
      name: "snickers protein",
      price: 18,
      category: "SNACKS",
      location: "cantina",
      barcode: "5000159516211",
    },
    {
      id: "45",
      name: "kitkat chunky",
      price: 8,
      category: "SNACKS",
      location: "cantina",
      barcode: "3800020412169",
    },
    {
      id: "46",
      name: "nuori chocolate",
      price: 12,
      category: "SNACKS",
      location: "cantina",
      barcode: "3800229511670",
    },
    {
      id: "47",
      name: "nuori coconut",
      price: 12,
      category: "SNACKS",
      location: "cantina",
      barcode: "3800229511663",
    },
    {
      id: "48",
      name: "oreo cake",
      price: 6,
      category: "SNACKS",
      location: "cantina",
      barcode: "7622210785114",
    },
    {
      id: "hidden2",
      name: "Produs Ascuns Cantina",
      price: 15,
      category: "ASCUNSE",
      location: "cantina",
      barcode: "888888888",
      hidden: true,
    },
    {
      id: "49",
      name: "biscuiti nuca&busuioc",
      price: 18,
      category: "SNACKS",
      location: "cantina",
      barcode: "5941893630248",
    },
    {
      id: "50",
      name: "biscuiti lavanda&mei",
      price: 18,
      category: "SNACKS",
      location: "cantina",
      barcode: "5941893630279",
    },
    {
      id: "51",
      name: "biscuiti lamaie&telina",
      price: 18,
      category: "SNACKS",
      location: "cantina",
      barcode: "5941893630286",
    },
    {
      id: "52",
      name: "biscuiti cocos&merisor",
      price: 18,
      category: "SNACKS",
      location: "cantina",
      barcode: "5941893630262",
    },
    {
      id: "53",
      name: "biscuiti cacao&mirodenii",
      price: 18,
      category: "SNACKS",
      location: "cantina",
      barcode: "5941893630330",
    },
    {
      id: "54",
      name: "biscuiti coacaze&trandafir",
      price: 18,
      category: "SNACKS",
      location: "cantina",
      barcode: "5941893630316",
    },
    {
      id: "55",
      name: "turta dulce",
      price: 18,
      category: "SNACKS",
      location: "cantina",
      barcode: "5941893630408",
    },
    {
      id: "56",
      name: "coltunasi",
      price: 20,
      category: "SNACKS",
      location: "cantina",
      barcode: "5941893630415",
    },
    {
      id: "57",
      name: "popcorn choco",
      price: 17,
      category: "SNACKS",
      location: "cantina",
      barcode: "8710998454786",
    },
    {
      id: "58",
      name: "covrigei frageziti cu vin masline 80g",
      price: 9,
      category: "SNACKS",
      location: "cantina",
      barcode: "5941143026166",
    },
    {
      id: "59",
      name: "popcorn caramel",
      price: 17,
      category: "SNACKS",
      location: "cantina",
      barcode: "8710998454779",
    },
    {
      id: "60",
      name: "covrigei frageziti cu vin alb 100g",
      price: 8,
      category: "SNACKS",
      location: "cantina",
      barcode: "5941143019625",
    },
    {
      id: "61",
      name: "mikso remolacha",
      price: 16.5,
      category: "SNACKS",
      location: "cantina",
      barcode: "8437016869253",
    },
    {
      id: "62",
      name: "covrigei frageziti cu vin rosu 100g",
      price: 8,
      category: "SNACKS",
      location: "cantina",
      barcode: "5941143021055",
    },
    {
      id: "63",
      name: "mikso chirivia",
      price: 16.5,
      category: "SNACKS",
      location: "cantina",
      barcode: "8437016869024",
    },
    {
      id: "64",
      name: "mikso boniato",
      price: 16.5,
      category: "SNACKS",
      location: "cantina",
      barcode: "8437016869017",
    },
    {
      id: "65",
      name: "bruschette maretti usturoi 70g",
      price: 7.5,
      category: "SNACKS",
      location: "cantina",
      barcode: "3800205870517",
    },
    {
      id: "66",
      name: "joe original vanilie 160g",
      price: 15,
      category: "SNACKS",
      location: "cantina",
      barcode: "7613287354303",
    },
    {
      id: "67",
      name: "tort de biscuiti 150g",
      price: 14,
      category: "SNACKS",
      location: "cantina",
      barcode: "6425682000720",
    },
    {
      id: "68",
      name: "ovaz-bar arahide 60g",
      price: 11,
      category: "SNACKS",
      location: "cantina",
      barcode: "5941893630125",
    },
    {
      id: "69",
      name: "ovaz-bar ciocolata 60g",
      price: 11,
      category: "SNACKS",
      location: "cantina",
      barcode: "5941893630149",
    },
    {
      id: "70",
      name: "baton umplut cocos vegan 60g",
      price: 11,
      category: "SNACKS",
      location: "cantina",
      barcode: "5941893630026",
    },
    {
      id: "71",
      name: "prajitura nuca si magiun prune 150g",
      price: 20,
      category: "SNACKS",
      location: "cantina",
      barcode: "5941905045206",
    },
    {
      id: "72",
      name: "prajitura ciocolata si arahide 150g",
      price: 20,
      category: "SNACKS",
      location: "cantina",
      barcode: "5941905045220",
    },
    {
      id: "73",
      name: "baton umplut magiun de prune vegan 60g",
      price: 11,
      category: "SNACKS",
      location: "cantina",
      barcode: "5941893630019",
    },
    {
      id: "74",
      name: "nutribon mix aventura 150g",
      price: 22,
      category: "SNACKS",
      location: "cantina",
      barcode: "5941904600369",
    },
    {
      id: "75",
      name: "nutribon mix drumetii 150g",
      price: 22,
      category: "SNACKS",
      location: "cantina",
      barcode: "5941904600321",
    },
    {
      id: "76",
      name: "covrigei frageziti cu unt grand papa 100g",
      price: 9,
      category: "SNACKS",
      location: "cantina",
      barcode: "5941896700788",
    },
    {
      id: "77",
      name: "bruschette maretti cheese 70g",
      price: 7.5,
      category: "SNACKS",
      location: "cantina",
      barcode: "3800205875604",
    },
    {
      id: "78",
      name: "toffifee 125g",
      price: 20,
      category: "SNACKS",
      location: "cantina",
      barcode: "4014400400007",
    },
    {
      id: "79",
      name: "covrigi grau intreg 230g",
      price: 15,
      category: "SNACKS",
      location: "cantina",
      barcode: "5941143024117",
    },
    {
      id: "80",
      name: "biskrem cocoa 160g",
      price: 20,
      category: "SNACKS",
      location: "cantina",
      barcode: "5941664006814",
    },
    {
      id: "81",
      name: "biscuite umplut crema curmale vegan 60g",
      price: 9,
      category: "SNACKS",
      location: "cantina",
      barcode: "5941893630088",
    },
    {
      id: "82",
      name: "eugenia cacao 36g",
      price: 2.5,
      category: "SNACKS",
      location: "cantina",
      barcode: "5941006101566",
    },
    {
      id: "83",
      name: "govinda ciocolata vegana 100g",
      price: 22,
      category: "SNACKS",
      location: "cantina",
      barcode: "5941905045299",
    },
    {
      id: "84",
      name: "ambrozia truffe vegane 140g",
      price: 22,
      category: "SNACKS",
      location: "cantina",
      barcode: "5941893630446",
    },
    {
      id: "85",
      name: "biscuiti tabiet miere 110g",
      price: 12,
      category: "SNACKS",
      location: "cantina",
      barcode: "5941896700160",
    },
    {
      id: "86",
      name: "joe noir 160g",
      price: 18,
      category: "SNACKS",
      location: "cantina",
      barcode: "7613287354341",
    },
    {
      id: "87",
      name: "twix caramel centres 144g",
      price: 20,
      category: "SNACKS",
      location: "cantina",
      barcode: "5060402907708",
    },
    {
      id: "88",
      name: "joe lamaie 117g",
      price: 12,
      category: "SNACKS",
      location: "cantina",
      barcode: "8445290159670",
    },
    {
      id: "89",
      name: "la gustosa lemon 150g",
      price: 12,
      category: "SNACKS",
      location: "cantina",
      barcode: "5902768862546",
    },
    {
      id: "90",
      name: "la gustosa hazelnut 150g",
      price: 12,
      category: "SNACKS",
      location: "cantina",
      barcode: "5902768862515",
    },
    {
      id: "91",
      name: "la gustosa chocolate 150g",
      price: 12,
      category: "SNACKS",
      location: "cantina",
      barcode: "5902768862508",
    },
    {
      id: "92",
      name: "la gustosa coconut 150g",
      price: 12,
      category: "SNACKS",
      location: "cantina",
      barcode: "5902768862522",
    },
    {
      id: "93",
      name: "la gustosa apple 150g",
      price: 12,
      category: "SNACKS",
      location: "cantina",
      barcode: "5902431560700",
    },
    {
      id: "94",
      name: "biscuiti peanuts sugar free 135g",
      price: 14,
      category: "SNACKS",
      location: "cantina",
      barcode: "5902431564791",
    },
    {
      id: "95",
      name: "biscuiti choco fit 135g",
      price: 12,
      category: "SNACKS",
      location: "cantina",
      barcode: "5902768865547",
    },
    {
      id: "96",
      name: "biscuiti choco gutti chocolate 160g",
      price: 12,
      category: "SNACKS",
      location: "cantina",
      barcode: "5902768862553",
    },
    {
      id: "97",
      name: "biscuiti choco gutti hazelnut 160g",
      price: 12,
      category: "SNACKS",
      location: "cantina",
      barcode: "5902768862560",
    },
    {
      id: "98",
      name: "sirop 250ml",
      price: 27,
      category: "SNACKS",
      location: "cantina",
      barcode: "",
    },
    {
      id: "99",
      name: "punch club negroni 250ml",
      price: 15,
      category: "BAUTURI",
      location: "cantina",
      barcode: "6427953005144",
    },
    {
      id: "100",
      name: "punch club gin tonic 250ml",
      price: 15,
      category: "BAUTURI",
      location: "cantina",
      barcode: "6427953005182",
    },
    {
      id: "101",
      name: "punch club grapefruit 250ml",
      price: 15,
      category: "BAUTURI",
      location: "cantina",
      barcode: "4744429010801",
    },
    {
      id: "102",
      name: "punch club aperitivo 250ml",
      price: 15,
      category: "BAUTURI",
      location: "cantina",
      barcode: "6427953005151",
    },
    {
      id: "103",
      name: "punch club moscow 250ml",
      price: 15,
      category: "BAUTURI",
      location: "cantina",
      barcode: "6427953005175",
    },
    {
      id: "104",
      name: "fresh portocale rosii",
      price: 16,
      category: "FRESH",
      location: "cantina",
      barcode: "",
    },
    {
      id: "1041",
      name: "fanta pet 0.5",
      price: 8.2,
      category: "BAUTURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "105",
      name: "energy drink",
      price: 15,
      category: "FRESH",
      location: "cantina",
      barcode: "",
    },
    {
      id: "106",
      name: "fresh grapefruit",
      price: 16,
      category: "FRESH",
      location: "cantina",
      barcode: "",
    },
    {
      id: "107",
      name: "limonada cu menta",
      price: 10,
      category: "FRESH",
      location: "cantina",
      barcode: "",
    },
    {
      id: "108",
      name: "fresh de portocale",
      price: 10,
      category: "FRESH",
      location: "cantina",
      barcode: "",
    },
    {
      id: "109",
      name: "immunity potion",
      price: 15,
      category: "FRESH",
      location: "cantina",
      barcode: "",
    },
    {
      id: "110",
      name: "suc sfecla si morcov",
      price: 17,
      category: "FRESH",
      location: "cantina",
      barcode: "",
    },
    {
      id: "111",
      name: "iaurt cu musli si miere",
      price: 7.2,
      category: "FRESH",
      location: "cantina",
      barcode: "",
    },
    {
      id: "112",
      name: "SANA/CHEFIR/LAPTE BATUT",
      price: 9,
      category: "MIC DEJUN",
      location: "cantina",
      barcode: "",
    },
    {
      id: "113",
      name: "merci asorted milk",
      price: 35,
      category: "SNACKS",
      location: "cantina",
      barcode: "4014400901405",
    },
    {
      id: "114",
      name: "merci asorted",
      price: 35,
      category: "SNACKS",
      location: "cantina",
      barcode: "4014400901191",
    },
    {
      id: "115",
      name: "pergale dark classic",
      price: 20,
      category: "SNACKS",
      location: "cantina",
      barcode: "4770179999042",
    },
    {
      id: "116",
      name: "pergale milk desserts",
      price: 20,
      category: "SNACKS",
      location: "cantina",
      barcode: "4770179998366",
    },
    {
      id: "117",
      name: "pergale milk hazelnut",
      price: 20,
      category: "SNACKS",
      location: "cantina",
      barcode: "4770179998397",
    },
    {
      id: "118",
      name: "pergale milk classic",
      price: 20,
      category: "SNACKS",
      location: "cantina",
      barcode: "4770179998656",
    },
    {
      id: "119",
      name: "MENIU 28.11",
      price: 28.11,
      category: "MENIURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "120",
      name: "MENIU 36.74",
      price: 36.74,
      category: "MENIURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "121",
      name: "MENIU 42.81",
      price: 42.81,
      category: "MENIURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "122",
      name: "MENIU 42.81",
      price: 42.81,
      category: "MENIURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "123",
      name: "MENIU PREMIUM",
      price: 39.35,
      category: "MENIURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "124",
      name: "FEL PRINCIPAL",
      price: 20.89,
      category: "MENIURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "125",
      name: "GARNITURA",
      price: 10.45,
      category: "MENIURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "126",
      name: "SALATA",
      price: 9.4,
      category: "MENIURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "127",
      name: "CIORBA",
      price: 10.45,
      category: "MENIURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "128",
      name: "CHIFLA MARE",
      price: 3.5,
      category: "MENIURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "129",
      name: "CHIFLA MICA",
      price: 2.5,
      category: "MENIURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "130",
      name: "FEL PRINCIPAL PREMIUM",
      price: 32,
      category: "MENIURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "131",
      name: "GARNITURA PREMIUM",
      price: 17,
      category: "MENIURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "132",
      name: "OU PRAJIT",
      price: 3.3,
      category: "MENIURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "133",
      name: "BETE DE LEGUME",
      price: 13,
      category: "MENIURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "134",
      name: "SHAORMA DE PUI",
      price: 36.9,
      category: "MENIURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "135",
      name: "SHAORMA DE VITA",
      price: 39.9,
      category: "MENIURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "136",
      name: "LIVE SALAD",
      price: 39.35,
      category: "MENIURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "137",
      name: "SOS",
      price: 3,
      category: "MENIURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "138",
      name: "ARDEI IUTE",
      price: 2,
      category: "MENIURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "139",
      name: "CRUTOANE",
      price: 2.5,
      category: "MENIURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "140",
      name: "KETCHUP",
      price: 1.2,
      category: "MENIURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "141",
      name: "BRANZA-SMANTANA",
      price: 6,
      category: "MENIURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "142",
      name: "MAIONEZA",
      price: 1.2,
      category: "MENIURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "143",
      name: "MITITEI",
      price: 5,
      category: "MENIURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "144",
      name: "QUICHE",
      price: 7.2,
      category: "MIC DEJUN",
      location: "cantina",
      barcode: "",
    },
    {
      id: "145",
      name: "SW TOAST OU",
      price: 12,
      category: "MIC DEJUN",
      location: "cantina",
      barcode: "",
    },
    {
      id: "146",
      name: "OMLETA COMPUSA",
      price: 20,
      category: "MIC DEJUN",
      location: "cantina",
      barcode: "",
    },
    {
      id: "147",
      name: "CRISPY BACON",
      price: 4.2,
      category: "MIC DEJUN",
      location: "cantina",
      barcode: "",
    },
    {
      id: "148",
      name: "OU OCHI",
      price: 4.2,
      category: "MIC DEJUN",
      location: "cantina",
      barcode: "",
    },
    {
      id: "149",
      name: "CARNATI",
      price: 6.9,
      category: "MIC DEJUN",
      location: "cantina",
      barcode: "",
    },
    {
      id: "150",
      name: "CARTOFI ROASTY",
      price: 4.5,
      category: "MIC DEJUN",
      location: "cantina",
      barcode: "",
    },
    {
      id: "151",
      name: "PINSA",
      price: 7.5,
      category: "MIC DEJUN",
      location: "cantina",
      barcode: "",
    },
    {
      id: "152",
      name: "ROSIE",
      price: 4.5,
      category: "MIC DEJUN",
      location: "cantina",
      barcode: "",
    },
    {
      id: "153",
      name: "CASTRAVETE",
      price: 4.5,
      category: "MIC DEJUN",
      location: "cantina",
      barcode: "",
    },
    {
      id: "154",
      name: "IAURT CU MIERE SI MUSLI",
      price: 7.2,
      category: "MIC DEJUN",
      location: "cantina",
      barcode: "",
    },
    {
      id: "155",
      name: "FRUCT",
      price: 3.3,
      category: "MIC DEJUN",
      location: "cantina",
      barcode: "",
    },
    {
      id: "156",
      name: "HUMMUS",
      price: 9.9,
      category: "MIC DEJUN",
      location: "cantina",
      barcode: "",
    },
    {
      id: "157",
      name: "SALATA DE VINETE",
      price: 9.9,
      category: "MIC DEJUN",
      location: "cantina",
      barcode: "",
    },
    {
      id: "158",
      name: "SALATA DE ICRE",
      price: 9.9,
      category: "MIC DEJUN",
      location: "cantina",
      barcode: "",
    },
    {
      id: "159",
      name: "FASOLE BATUTA",
      price: 9.9,
      category: "MIC DEJUN",
      location: "cantina",
      barcode: "",
    },
    {
      id: "160",
      name: "CROISSANT",
      price: 6.9,
      category: "PATISERIE",
      location: "cantina",
      barcode: "",
    },
    {
      id: "161",
      name: "TRIGON CU BRANZA",
      price: 9,
      category: "PATISERIE",
      location: "cantina",
      barcode: "",
    },
    {
      id: "162",
      name: "RULOU DUBLU",
      price: 9,
      category: "PATISERIE",
      location: "cantina",
      barcode: "",
    },
    {
      id: "163",
      name: "RULOU SIMPLU",
      price: 8,
      category: "PATISERIE",
      location: "cantina",
      barcode: "",
    },
    {
      id: "164",
      name: "FOIETAJ MERE",
      price: 9,
      category: "PATISERIE",
      location: "cantina",
      barcode: "",
    },
    {
      id: "165",
      name: "MELC",
      price: 9,
      category: "PATISERIE",
      location: "cantina",
      barcode: "",
    },
    {
      id: "166",
      name: "STRUDEL PECAN",
      price: 6.9,
      category: "PATISERIE",
      location: "cantina",
      barcode: "",
    },
    {
      id: "167",
      name: "PAIN AU CHOCOLAT",
      price: 6.9,
      category: "PATISERIE",
      location: "cantina",
      barcode: "",
    },
    {
      id: "168",
      name: "FOIETAJ CU SUNCA",
      price: 9,
      category: "PATISERIE",
      location: "cantina",
      barcode: "",
    },
    {
      id: "169",
      name: "CROISSANT PROSCIUTTO",
      price: 12.9,
      category: "PATISERIE",
      location: "cantina",
      barcode: "",
    },
    {
      id: "170",
      name: "SANDWICH",
      price: 16.5,
      category: "PATISERIE",
      location: "cantina",
      barcode: "",
    },
    {
      id: "171",
      name: "jumex ananas si cocos",
      price: 12.5,
      category: "BAUTURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "172",
      name: "jumex mango",
      price: 12.5,
      category: "BAUTURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "173",
      name: "jumex capsuni si banana",
      price: 12.5,
      category: "BAUTURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "174",
      name: "jumex ananas",
      price: 12.5,
      category: "BAUTURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "175",
      name: "jumex ananas",
      price: 12.5,
      category: "BAUTURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "176",
      name: "jumex mere",
      price: 12.5,
      category: "BAUTURI",
      location: "cantina",
      barcode: "",
    },
    {
      id: "177",
      name: "schweppes pink doza 0.33",
      price: 7,
      category: "BAUTURI",
      location: "cantina",
      barcode: "5942321002835",
    },
    {
      id: "178",
      name: "sprite doza 0.33",
      price: 7,
      category: "BAUTURI",
      location: "cantina",
      barcode: "5942321002460",
    },
    {
      id: "179",
      name: "cola ciob normal 0.33",
      price: 7,
      category: "BAUTURI",
      location: "cantina",
      barcode: "59492597",
    },
    {
      id: "180",
      name: "mars 70g",
      price: 15,
      category: "SNACKS",
      location: "cantina",
      barcode: "",
    },
    {
      id: "181",
      name: "la gustosa macchiato 150g",
      price: 12,
      category: "SNACKS",
      location: "cantina",
      barcode: "5902768862539",
    },
    {
      id: "182",
      name: "govinda visine",
      price: 22,
      category: "SNACKS",
      location: "cantina",
      barcode: "5941905045305",
    },
    {
      id: "183",
      name: "keto go on capsuni",
      price: 0,
      category: "SNACKS",
      location: "cantina",
      barcode: "5900617047076",
    },
    {
      id: "184",
      name: "keto go on cioco lapte",
      price: 0,
      category: "SNACKS",
      location: "cantina",
      barcode: "5900617035882",
    },
    {
      id: "185",
      name: "keto go on cocos",
      price: 0,
      category: "SNACKS",
      location: "cantina",
      barcode: "5900617046710",
    },
    {
      id: "186",
      name: "keto go on peanut butter",
      price: 0,
      category: "SNACKS",
      location: "cantina",
      barcode: "5900617044341",
    },
    {
      id: "187",
      name: "servetele sala",
      price: 0,
      category: "CONSUMABILE",
      location: "cantina",
      barcode: "",
    },
    {
      id: "188",
      name: "casolete carton mari sala",
      price: 0,
      category: "CONSUMABILE",
      location: "cantina",
      barcode: "",
    },
    {
      id: "189",
      name: "casolete carton mici sala",
      price: 0,
      category: "CONSUMABILE",
      location: "cantina",
      barcode: "",
    },
    {
      id: "190",
      name: "role hartie",
      price: 0,
      category: "CONSUMABILE",
      location: "cantina",
      barcode: "",
    },
    {
      id: "191",
      name: "manusi S",
      price: 0,
      category: "CONSUMABILE",
      location: "cantina",
      barcode: "",
    },
    {
      id: "192",
      name: "manusi M",
      price: 0,
      category: "CONSUMABILE",
      location: "cantina",
      barcode: "",
    },
    {
      id: "193",
      name: "manusi L",
      price: 0,
      category: "CONSUMABILE",
      location: "cantina",
      barcode: "",
    },
    {
      id: "194",
      name: "manusi XL",
      price: 0,
      category: "CONSUMABILE",
      location: "cantina",
      barcode: "",
    },
    {
      id: "195",
      name: "scobitori",
      price: 0,
      category: "CONSUMABILE",
      location: "cantina",
      barcode: "",
    },
    {
      id: "196",
      name: "tacamuri",
      price: 0,
      category: "CONSUMABILE",
      location: "cantina",
      barcode: "",
    },
    {
      id: "197",
      name: "pungi spoonful",
      price: 0,
      category: "CONSUMABILE",
      location: "cantina",
      barcode: "",
    },
  ];

  localStorage.setItem("viva_products", JSON.stringify(vivaProducts));
  localStorage.setItem("cantina_products", JSON.stringify(cantinaProducts));

  return location === "viva" ? vivaProducts : cantinaProducts;
};

export const getProducts = (location: "cantina" | "viva") => {
  const key = `${location}_products`;
  const products = localStorage.getItem(key);
  return products ? JSON.parse(products) : initializeProducts(location);
};

export const addProduct = (product: Product) => {
  const key = `${product.location}_products`;
  const products = getProducts(product.location);
  localStorage.setItem(key, JSON.stringify([...products, product]));
};

export const updateProduct = (product: Product) => {
  const key = `${product.location}_products`;
  const products = getProducts(product.location);
  const updatedProducts = products.map((p: Product) =>
    p.id === product.id ? product : p
  );
  localStorage.setItem(key, JSON.stringify(updatedProducts));
};
